config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  get 'products/show'
  get 'products/home'
  get 'products/garden'
  get 'products/art'
  get 'categories/index'
  get 'categories/show'
  get 'categories/home'
  get 'categories/garden'
  get 'categories/art'
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :title, presence: true, uniqueness: true
  validates :main, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :title, presence: true, uniqueness: true
  validates :sub_category_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @products = Product.where(category_id: @category.id)
  end

    def home
    @categories = Category.where(main: 'home')
  end

    def garden
    @categories = Category.where(main: 'garden')
  end

    def art
    @categories = Category.where(main: 'art')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!
  def home
  end

  def about
  end

  def contact
  end

  def social_outreach
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @products = Product.where(category_id: @category.id)
    @category = Category.find(params[:id])
  end

  def show
    @product = Product.find(params[:category_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/art.html.erb
<div class="container d-flex justify-content-center" >

    <div class="lobbies" id="lobby">
      <% @categories.each do |category| %>
      <%= render 'shared/catcard', category: category %>
      <% end %>
    </div>

</div>

    <div>
  <%= link_to "Go Back", categories_path, class: "btn btn-gradient" %>
    </div>

app/views/categories/garden.html.erb
<div class="container d-flex justify-content-center" >

    <div class="lobbies" id="lobby">
      <% @categories.each do |category| %>
      <%= render 'shared/catcard', category: category %>
      <% end %>
    </div>

</div>

    <div>
  <%= link_to "Go Back", categories_path, class: "btn btn-gradient" %>
    </div>

app/views/categories/home.html.erb
<div class="container d-flex justify-content-center" >

    <div class="lobbies" id="lobby">
      <% @categories.each do |category| %>
      <%= render 'shared/catcard', category: category %>
      <% end %>
    </div>

</div>

    <div>
  <%= link_to "Go Back", categories_path, class: "btn btn-gradient" %>
    </div>

app/views/categories/index.html.erb
<div class="category-container">
  <div class="row" style="padding:45px;justify-content: center;">
    <div class="col-8">
      <%= link_to categories_home_path do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_url'indoors.jpg'%>)">
            For the Home
          </div>
        <% end %>
      </div>
    </div>

    <div class="row" style="padding:45px;justify-content: center;">
      <div class="col-8">
        <%= link_to categories_garden_path do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_url'garden.jpeg'%>">
            Garden
          </div>
        <% end %>
      </div>
    </div>


  <div class="row" style="padding:45px; justify-content: center;">
  <div class="col-8">
    <%= link_to categories_art_path do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_url'art.jpg'%>)">
          Art
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container d-flex justify-content-center" >

    <div class="lobbies" id="lobby">
      <% @products.each do |product| %>
<%= link_to category_product_path(product) do %>
  <div class="card-trip">
    <div class="card-image" style="background: rgb(2,0,36); background-image:linear-gradient(0deg, rgba(2,0,36,1) 0%, rgba(0,0,0,1) 2%, rgba(0,0,0,0) 50%), url(<%= asset_path product.image %>); border-radius:10px; height:200px; background-size:cover; background-position: center; padding:24px;">
    </div>
      <div class="card-trip-infos">
      <div>
      <h2><%= product.title %></h2>
      </div>
    </div>
  </div>
<% end %>
 <% end %>
    </div>

</div>
<% if @category.main == 'art' %>
  <div>
  <%= link_to 'Go Back', categories_art_path, class: "btn btn-gradient" %>
  </div>
<% elsif @category.main == 'home' %>
  <div>
  <%= link_to 'Go Back', categories_home_path, class: "btn btn-gradient" %>
  </div>
<% else %>
  <div>
  <%= link_to 'Go Back', categories_garden_path, class: "btn btn-gradient" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eco-conscious crafts</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="main-container">
    <%= render 'shared/flashes' %>
    <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_url'green_living_1.jpg'%>); background-size: cover;">
    <div class="row">
  <div class="container">
      <div class="col-6">

    <h1>Eco-conscious Crafts brings <strong> a greener lifestyle to your home!</h1>
    <p> Our stylish, eco-friendly products blend craftsmanship and art, making for a truly unique range.</p>
      </div>
    </div>
  </div>
</div>
<div id="carousel-thumb" class="carousel slide carousel-fade carousel-thumbnails" data-ride="carousel">
  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(88).jpg"
        alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(121).jpg"
        alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://mdbootstrap.com/img/Photos/Slides/img%20(31).jpg"
        alt="Third slide">
    </div>
  </div>
  <!--/.Slides-->
  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-thumb" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-thumb" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-thumb" data-slide-to="0" class="active">
      <img src="https://mdbootstrap.com/img/Photos/Others/Carousel-thumbs/img%20(88).jpg" width="100">
    </li>
    <li data-target="#carousel-thumb" data-slide-to="1">
      <img src="https://mdbootstrap.com/img/Photos/Others/Carousel-thumbs/img%20(121).jpg" width="100">
    </li>
    <li data-target="#carousel-thumb" data-slide-to="2">
      <img src="https://mdbootstrap.com/img/Photos/Others/Carousel-thumbs/img%20(31).jpg" width="100">
    </li>
  </ol>
</div>

app/views/products/art.html.erb
<h1>Products#art</h1>
<p>Find me in app/views/products/art.html.erb</p>

app/views/products/garden.html.erb
<h1>Products#garden</h1>
<p>Find me in app/views/products/garden.html.erb</p>

app/views/products/home.html.erb
<h1>Products#home</h1>
<p>Find me in app/views/products/home.html.erb</p>

app/views/products/index.html.erb
<div class="container d-flex justify-content-center" >

    <div class="lobbies" id="lobby">
      <% @products.each do |product| %>
<%= link_to category_products_path(product) do %>
  <div class="card-trip">
    <div class="card-image" style="background: rgb(2,0,36); background-image:linear-gradient(0deg, rgba(2,0,36,1) 0%, rgba(0,0,0,1) 2%, rgba(0,0,0,0) 50%), url(<%= asset_path product.image %>); border-radius:10px; height:200px; background-size:cover; background-position: center; padding:24px;">
    </div>
      <div class="card-trip-infos">
      <div>
      <h2><%= product.title %></h2>
      </div>
    </div>
  </div>
<% end %>
 <% end %>
    </div>

</div>
<% if @category.main == 'art' %>
  <div>
  <%= link_to 'Go Back', categories_art_path, class: "btn btn-gradient" %>
  </div>
<% elsif @category.main == 'home' %>
  <div>
  <%= link_to 'Go Back', categories_home_path, class: "btn btn-gradient" %>
  </div>
<% else %>
  <div>
  <%= link_to 'Go Back', categories_garden_path, class: "btn btn-gradient" %>
  </div>
<% end %>

app/views/products/show.html.erb
<div>
    <%= render 'shared/product_show_card' %>
</div>

<div>
<%= link_to 'Go Back', :back, class: "btn btn-gradient" %>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Eco-conscious Crafts. <strong> Bringing upcycled home accessories </strong>to <strong> those wanting a greener lifestyle </strong>!</h1>
    <p> Our stylish, eco-friendly products blend craftsmanship and art, making for a truly unique range.</p>
    <a class="btn btn-flat" href="#">Browse our products</a>
<%= link_to "Browse Products", "categories_path", class: "btn btn-gradient" %>
  </div>
</div>

app/views/shared/_button.html.erb
<div>
<%= link_to "Go Back", "#", class: "btn btn-gradient" %>
</div>

app/views/shared/_card.html.erb
<%= link_to category_product_path(@product) do %>
  <div class="card-trip">
    <div class="card-image" style="background: rgb(2,0,36); background-image:linear-gradient(0deg, rgba(2,0,36,1) 0%, rgba(0,0,0,1) 2%, rgba(0,0,0,0) 50%), url(<%= asset_path product.image %>); border-radius:10px; height:200px; background-size:cover; background-position: center;">
    </div>
      <div class="card-trip-infos">
      <div>
      <h2><%= product.title %></h2>
      <p>product.description</p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_catcard.html.erb
<%= link_to category_path(category) do %>
  <div class="card-trip">
    <div class="card-image" style="background: rgb(2,0,36); background-image:linear-gradient(0deg, rgba(2,0,36,1) 0%, rgba(0,0,0,1) 2%, rgba(0,0,0,0) 50%), url(<%= asset_path category.photo %>); border-radius:10px; height:200px; background-size:cover; background-position: center;">
    </div>
      <div class="card-trip-infos">
      <div>
      <h2><%= category.title %></h2>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

    <div class="logo" style="color:white; background: rgb(2,0,36); background-image:linear-gradient(0deg, rgba(2,0,36,1) 0%, rgba(0,0,0,1) 2%, rgba(0,0,0,0) 50%), url(<%= asset_path 'bulb.jpg' %>); border-radius:50%; height:50px; background-size:cover; background-position: center; padding:24px;">
    </div>

  <%= link_to "Home", pages_home_path, class:"btn btn-ghost" %>

  <%= link_to "Products", categories_path, class:"btn btn-ghost" %>
  <%= link_to "About", pages_about_path, class:"btn btn-ghost" %>
  <%= link_to "Contact", pages_contact_path, class:"btn btn-ghost" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <!-- <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li> -->
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-ghost" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_product_show_card.html.erb
<div class="card" style="width: 50%;">
    <div class="card-img-top" style=" height: 50vh; background: rgb(2,0,36); background-image:linear-gradient(0deg, rgba(2,0,36,1) 0%, rgba(0,0,0,1) 2%, rgba(0,0,0,0) 50%), url(<%= asset_path @product.image %>); border-radius:10px; height:200px; background-size:cover; background-position: center; padding:24px;">
    </div>  <div class="card-body">
    <p class="card-text"><%= @product.description %></p>
  </div>
  <p>Amount: <%= humanized_money_with_symbol(@product.price) %></p>
  <div>
    <%= link_to 'Purchase', "#", class: "btn btn-gradient" %>
  </div>
</div>